name: deploy to firebase dev server review channel
'on': 
  push: 
    branch:
      - '!release'
      - '!main'
      - '!dev'
jobs:
  build_and_deploy_to_dev_review:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          expires: 7d
          projectId: dev-bv