name: Deploy to review channel of dev server
'on': 
  push: 
    branch:
      - '!release'
      - '!main'
      - '!dev'
jobs:
  build:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean install
        run: npm ci 
      - name: Build
        run: npm run build
#  test:
#      - name: Test not implemented
  deploy:
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.DEV_BV_FIREBASE_TOKEN }}'
          expires: 7d
          projectId: '${{ secrets.DEV_PROJECT_ID }}'


          #TODO: Add cypress tests
          #TODO: Add jest tests