name : Release to live channael of production server
'on':
  push:
    branches:
      - main
jobs:
  build:
    name: Bluid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean install
        run: npm ci 
      - name: Build
        run: npm run build
#  test:
#      - name: test not implemented
  release:
    name: Release to live channael of production server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD_BV }}'
          channelId: live
          projectId: '${{ secrets.PROD_PROJECT_ID }}'
          
          
          #TODO: Add cypress tests
          #TODO: Add jest tests