name : release to firebase production server live channael
'on':
  push:
    branches:
      - main
jobs:
  build_and_release_to_prod_live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.PROD_BV_FIREBASE_TOKEN }}'
          channelId: live
          projectId: prod-bv